title: UT JSG Open-Source Hackathon 2024
description: Documentation of the Jackson School of Geosciences Open-Source Hackathon focused on computational reproducibility and open-source software practices within geoscience research.

theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  
author:
  name: Cameron Cummins
  email: cameron.cummins@utexas.edu